<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>za.co.sindi</groupId>
	<artifactId>sindi-sqlmanager</artifactId>
	<version>1.0.0</version>
	<name>Sindi SQLManager</name>
	<description>A library that makes it easy to execute SQL queries using the
		JDBC API. The developer only worries about data.</description>

	<developers>
		<developer>
			<name>Buhake Sindi</name>
			<timezone>+2</timezone>
			<roles>
				<role>PROJECT LEAD</role>
			</roles>
			<organization>Sindi Technologies (Pty) Ltd</organization>
			<organizationUrl>https://www.sindi.co.za</organizationUrl>
		</developer>
	</developers>

	<licenses>
		<license>
			<name>The Apache Software License, Version 2.0</name>
			<url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
			<distribution>repo</distribution>
		</license>
	</licenses>

	<scm>
		<connection>scm:git:git://github.com/sinditech/sindi-sqlmanager.git</connection>
		<developerConnection>scm:git:git@sinditech/sindi-sqlmanager.git</developerConnection>
		<url>https://github.com/sinditech/sindi-sqlmanager</url>
		<tag>HEAD</tag>
	</scm>

	<repositories>
		<repository>
			<name>Central Portal Snapshots</name>
			<id>central-portal-snapshots</id>
			<url>https://central.sonatype.com/repository/maven-snapshots/</url>
			<releases>
				<enabled>false</enabled>
			</releases>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
		</repository>
	</repositories>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.report.sourceEncoding>UTF-8</project.report.sourceEncoding>
		<maven.compiler.source>17</maven.compiler.source>
		<maven.compiler.target>17</maven.compiler.target>
	</properties>

	<dependencies>
		<!--
		<dependency>
			<groupId>za.co.sindi</groupId>
			<artifactId>sindi-commons</artifactId>
			<version>1.0.0</version>
		</dependency>
		-->
		<!--
		https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter-api -->
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter-api</artifactId>
			<version>6.0.1</version>
			<scope>test</scope>
		</dependency>
	</dependencies>
	
	<build>
		<!-- Tell Maven that this is a Java 1.7 project -->
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.14.1</version>
			</plugin>
			<!-- Maven Sources plugin -->
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-source-plugin</artifactId>
				<version>3.4.0</version>
				<executions>
					<execution>
						<id>attach-sources</id>
						<goals>
							<goal>jar</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<!-- Maven Javadoc plugin -->
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-javadoc-plugin</artifactId>
				<version>3.12.0</version>
				<executions>
					<execution>
						<id>attach-javadocs</id>
						<goals>
							<goal>jar</goal>
						</goals>
						<configuration>
							<source>8</source>
							<doclint>none</doclint>
						</configuration>
					</execution>
				</executions>
				<configuration>
					<additionalOptions>
						<additionalOption>-Xdoclint:none</additionalOption>
					</additionalOptions>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.sonatype.central</groupId>
				<artifactId>central-publishing-maven-plugin</artifactId>
				<version>0.9.0</version>
				<extensions>true</extensions>
				<configuration>
					<publishingServerId>central</publishingServerId>
					<autoPublish>true</autoPublish>
					<waitUntil>published</waitUntil>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
	        	<artifactId>maven-gpg-plugin</artifactId>
				<version>3.2.8</version>
			</plugin>
		</plugins>
	</build>
	
	<profiles>
		<profile>
            <id>sign</id>
            <activation>
                <property>
                    <name>sign</name>
                </property>
            </activation>
            <build>
				<plugins>
					<!-- GPG Signed Components -->
			      	<plugin>
			        	<groupId>org.apache.maven.plugins</groupId>
			        	<artifactId>maven-gpg-plugin</artifactId>
			        	<version>3.2.8</version>
			        	<executions>
			          		<execution>
			            		<id>sign-artifacts</id>
			            		<phase>verify</phase>
			            		<goals>
			              			<goal>sign</goal>
			            		</goals>
			            		<configuration>
				              		<gpgArguments>
				                		<arg>--pinentry-mode</arg>
				                		<arg>loopback</arg>
				              		</gpgArguments>
			            		</configuration>
			          		</execution>
			          	</executions>
			      	</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>
</project>
