/**
 * 
 */
package za.co.sindi.sql.query;

/**
 * @author Bienfait Sindi
 * @since 02 April 2014
 *
 */
public interface PreparedQueryManager extends QueryManager {
	
	public BatchPreparedQuery createBatchPreparedQuery(String query);
	
	public <T> SelectablePreparedQuery<T> createSelectablePreparedQuery(String query);
	public <T> SelectablePreparedQuery<T> createSelectablePreparedQuery(String query, int resultSetType, int resultSetConcurrency);
	public <T> SelectablePreparedQuery<T> createSelectablePreparedQuery(String query, int resultSetType, int resultSetConcurrency, int resultSetHoldability);
	
	public InsertablePreparedQuery createInsertablePreparedQuery(String query);
	public InsertablePreparedQuery createInsertablePreparedQuery(String query, boolean autoGeneratedKeys);
	public InsertablePreparedQuery createInsertablePreparedQuery(String query, int[] primaryKeyColumnIndexes);
	public InsertablePreparedQuery createInsertablePreparedQuery(String query, String[] primaryKeyColumnNames);
	
	public UpdatablePreparedQuery createUpdatablePreparedQuery(String query);
}
