/**
 * 
 */
package za.co.sindi.sql.query;

/**
 * @author Bienfait Sindi
 * @since 02 April 2014
 *
 */
public interface QueryManager {
	
	public void close();
	public BatchQuery createBatchQuery();
	
	public CallableQuery createCallableQuery(String query);
	public CallableQuery createCallableQuery(String query, int resultSetType, int resultSetConcurrency);
	public CallableQuery createCallableQuery(String query, int resultSetType, int resultSetConcurrency, int resultSetHoldability);
	
	public <T> SelectableQuery<T> createSelectableQuery(String query);
	public <T> SelectableQuery<T> createSelectableQuery(String query, int resultSetType, int resultSetConcurrency);
	public <T> SelectableQuery<T> createSelectableQuery(String query, int resultSetType, int resultSetConcurrency, int resultSetHoldability);
	
	public InsertableQuery createInsertableQuery(String query);
	public InsertableQuery createInsertableQuery(String query, boolean autoGeneratedKeys);
	public InsertableQuery createInsertableQuery(String query, int[] primaryKeyColumnIndexes);
	public InsertableQuery createInsertableQuery(String query, String[] primaryKeyColumnNames);
	
	public UpdatableQuery createUpdatableQuery(String query);
}
