/**
 * 
 */
package za.co.sindi.sql.query.impl;

import java.sql.Connection;

import za.co.sindi.sql.query.BatchPreparedQuery;
import za.co.sindi.sql.query.InsertablePreparedQuery;
import za.co.sindi.sql.query.PreparedQueryManager;
import za.co.sindi.sql.query.SelectablePreparedQuery;
import za.co.sindi.sql.query.UpdatablePreparedQuery;

/**
 * @author Bienfait Sindi
 * @since 05 April 2014
 *
 */
public class DefaultPreparedQueryManager extends DefaultQueryManager implements PreparedQueryManager {

	/**
	 * @param connection
	 */
	public DefaultPreparedQueryManager(Connection connection) {
		super(connection);
		// TODO Auto-generated constructor stub
	}

	/* (non-Javadoc)
	 * @see za.co.sindi.sql.query.PreparedQueryManager#createBatchPreparedQuery(java.lang.String)
	 */
	@Override
	public BatchPreparedQuery createBatchPreparedQuery(String query) {
		// TODO Auto-generated method stub
		return new BatchUpdatePreparedQuery(getConnection(), query);
	}

	/* (non-Javadoc)
	 * @see za.co.sindi.sql.query.PreparedQueryManager#createSelectablePreparedQuery(java.lang.String)
	 */
	@Override
	public <T> SelectablePreparedQuery<T> createSelectablePreparedQuery(String query) {
		// TODO Auto-generated method stub
		return new SelectPreparedQuery<T>(getConnection(), query);
	}

	/* (non-Javadoc)
	 * @see za.co.sindi.sql.query.PreparedQueryManager#createSelectablePreparedQuery(java.lang.String, int, int)
	 */
	@Override
	public <T> SelectablePreparedQuery<T> createSelectablePreparedQuery(String query, int resultSetType, int resultSetConcurrency) {
		// TODO Auto-generated method stub
		return new SelectPreparedQuery<T>(getConnection(), query, resultSetType, resultSetConcurrency);
	}

	/* (non-Javadoc)
	 * @see za.co.sindi.sql.query.PreparedQueryManager#createSelectablePreparedQuery(java.lang.String, int, int, int)
	 */
	@Override
	public <T> SelectablePreparedQuery<T> createSelectablePreparedQuery(String query, int resultSetType, int resultSetConcurrency, int resultSetHoldability) {
		// TODO Auto-generated method stub
		return new SelectPreparedQuery<T>(getConnection(), query, resultSetType, resultSetConcurrency, resultSetHoldability);
	}
	
	/* (non-Javadoc)
	 * @see za.co.sindi.sql.query.PreparedQueryManager#createInsertablePreparedQuery(java.lang.String)
	 */
	@Override
	public InsertablePreparedQuery createInsertablePreparedQuery(String query) {
		// TODO Auto-generated method stub
		return new InsertPreparedQuery(getConnection(), query);
	}

	/* (non-Javadoc)
	 * @see za.co.sindi.sql.query.PreparedQueryManager#createInsertablePreparedQuery(java.lang.String, boolean)
	 */
	@Override
	public InsertablePreparedQuery createInsertablePreparedQuery(String query, boolean autoGeneratedKeys) {
		// TODO Auto-generated method stub
		return new InsertPreparedQuery(getConnection(), query, autoGeneratedKeys);
	}

	/* (non-Javadoc)
	 * @see za.co.sindi.sql.query.PreparedQueryManager#createInsertablePreparedQuery(java.lang.String, int[])
	 */
	@Override
	public InsertablePreparedQuery createInsertablePreparedQuery(String query, int[] primaryKeyColumnIndexes) {
		// TODO Auto-generated method stub
		return new InsertPreparedQuery(getConnection(), query, primaryKeyColumnIndexes);
	}

	/* (non-Javadoc)
	 * @see za.co.sindi.sql.query.PreparedQueryManager#createInsertablePreparedQuery(java.lang.String, java.lang.String[])
	 */
	@Override
	public InsertablePreparedQuery createInsertablePreparedQuery(String query, String[] primaryKeyColumnNames) {
		// TODO Auto-generated method stub
		return new InsertPreparedQuery(getConnection(), query, primaryKeyColumnNames);
	}

	/* (non-Javadoc)
	 * @see za.co.sindi.sql.query.PreparedQueryManager#createUpdatablePreparedQuery(java.lang.String)
	 */
	@Override
	public UpdatablePreparedQuery createUpdatablePreparedQuery(String query) {
		// TODO Auto-generated method stub
		return new UpdatePreparedQuery(getConnection(), query);
	}
}
