/**
 * 
 */
package za.co.sindi.sql.query.impl;

import java.sql.Connection;

import za.co.sindi.sql.query.AbstractQueryManager;
import za.co.sindi.sql.query.BatchQuery;
import za.co.sindi.sql.query.CallableQuery;
import za.co.sindi.sql.query.InsertableQuery;
import za.co.sindi.sql.query.QueryManager;
import za.co.sindi.sql.query.SelectableQuery;
import za.co.sindi.sql.query.UpdatableQuery;

/**
 * @author Bienfait Sindi
 * @since 05 April 2014
 *
 */
public class DefaultQueryManager extends AbstractQueryManager implements QueryManager {

	/**
	 * @param connection
	 */
	public DefaultQueryManager(Connection connection) {
		super(connection);
	}

	/* (non-Javadoc)
	 * @see za.co.sindi.sql.query.QueryManager#createBatchQuery()
	 */
	@Override
	public BatchQuery createBatchQuery() {
		// TODO Auto-generated method stub
		return new BatchUpdateQuery(getConnection());
	}

	/* (non-Javadoc)
	 * @see za.co.sindi.sql.query.QueryManager#createCallableQuery(java.lang.String)
	 */
	@Override
	public CallableQuery createCallableQuery(String query) {
		// TODO Auto-generated method stub
		return new StoredProcedureQuery(getConnection(), query);
	}

	/* (non-Javadoc)
	 * @see za.co.sindi.sql.query.QueryManager#createCallableQuery(java.lang.String, int, int)
	 */
	@Override
	public CallableQuery createCallableQuery(String query, int resultSetType, int resultSetConcurrency) {
		// TODO Auto-generated method stub
		return new StoredProcedureQuery(getConnection(), query, resultSetType, resultSetConcurrency);
	}

	/* (non-Javadoc)
	 * @see za.co.sindi.sql.query.QueryManager#createCallableQuery(java.lang.String, int, int, int)
	 */
	@Override
	public CallableQuery createCallableQuery(String query, int resultSetType, int resultSetConcurrency, int resultSetHoldability) {
		// TODO Auto-generated method stub
		return new StoredProcedureQuery(getConnection(), query, resultSetType, resultSetConcurrency, resultSetHoldability);
	}

	/* (non-Javadoc)
	 * @see za.co.sindi.sql.query.QueryManager#createSelectableQuery(java.lang.String)
	 */
	@Override
	public <T> SelectableQuery<T> createSelectableQuery(String query) {
		// TODO Auto-generated method stub
		return new SelectQuery<T>(getConnection(), query);
	}

	/* (non-Javadoc)
	 * @see za.co.sindi.sql.query.QueryManager#createSelectableQuery(java.lang.String, int, int)
	 */
	@Override
	public <T> SelectableQuery<T> createSelectableQuery(String query, int resultSetType, int resultSetConcurrency) {
		// TODO Auto-generated method stub
		return new SelectQuery<T>(getConnection(), query, resultSetType, resultSetConcurrency);
	}

	/* (non-Javadoc)
	 * @see za.co.sindi.sql.query.QueryManager#createSelectableQuery(java.lang.String, int, int, int)
	 */
	@Override
	public <T> SelectableQuery<T> createSelectableQuery(String query, int resultSetType, int resultSetConcurrency, int resultSetHoldability) {
		// TODO Auto-generated method stub
		return new SelectQuery<T>(getConnection(), query, resultSetType, resultSetConcurrency, resultSetHoldability);
	}

	/* (non-Javadoc)
	 * @see za.co.sindi.sql.query.QueryManager#createInsertableQuery(java.lang.String)
	 */
	@Override
	public InsertableQuery createInsertableQuery(String query) {
		// TODO Auto-generated method stub
		return new InsertQuery(getConnection(), query);
	}

	/* (non-Javadoc)
	 * @see za.co.sindi.sql.query.QueryManager#createInsertableQuery(java.lang.String, boolean)
	 */
	@Override
	public InsertableQuery createInsertableQuery(String query, boolean autoGeneratedKeys) {
		// TODO Auto-generated method stub
		return new InsertQuery(getConnection(), query, autoGeneratedKeys);
	}

	/* (non-Javadoc)
	 * @see za.co.sindi.sql.query.QueryManager#createInsertableQuery(java.lang.String, int[])
	 */
	@Override
	public InsertableQuery createInsertableQuery(String query, int[] primaryKeyColumnIndexes) {
		// TODO Auto-generated method stub
		return new InsertQuery(getConnection(), query, primaryKeyColumnIndexes);
	}

	/* (non-Javadoc)
	 * @see za.co.sindi.sql.query.QueryManager#createInsertableQuery(java.lang.String, java.lang.String[])
	 */
	@Override
	public InsertableQuery createInsertableQuery(String query, String[] primaryKeyColumnNames) {
		// TODO Auto-generated method stub
		return new InsertQuery(getConnection(), query, primaryKeyColumnNames);
	}

	/* (non-Javadoc)
	 * @see za.co.sindi.sql.query.QueryManager#createUpdatableQuery(java.lang.String)
	 */
	@Override
	public UpdatableQuery createUpdatableQuery(String query) {
		// TODO Auto-generated method stub
		return new UpdateQuery(getConnection(), query);
	}
}
