/**
 * 
 */
package za.co.sindi.sql.query.impl;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;

import za.co.sindi.sql.exception.QueryException;
import za.co.sindi.sql.handler.ResultSetHandler;
import za.co.sindi.sql.query.AbstractPreparedQuery;
import za.co.sindi.sql.query.InsertablePreparedQuery;
import za.co.sindi.sql.utils.SQLUtils;

/**
 * @author Bienfait Sindi
 * @since 05 April 2014
 *
 */
public class InsertPreparedQuery extends AbstractPreparedQuery implements InsertablePreparedQuery {

	private int updateCount;
	private Object generatedKeys;
	private ResultSetHandler<Object> generatedKeysResultSetHandler;
	private boolean autoGeneratedKeys;
	private PreparedStatement preparedStatement;
	
	/**
	 * 
	 * @param connection
	 * @param query
	 */
	public InsertPreparedQuery(Connection connection, String query) {
		this(connection, query, false);
	}
	
	/**
	 * 
	 * @param connection
	 * @param query
	 * @param autoGeneratedKeys
	 */
	public InsertPreparedQuery(Connection connection, String query, boolean autoGeneratedKeys) {
		super();
		
		try {
			if (autoGeneratedKeys) {
				preparedStatement = connection.prepareStatement(query, Statement.RETURN_GENERATED_KEYS);
			} else {
				preparedStatement = connection.prepareStatement(query);
			}
			this.autoGeneratedKeys = autoGeneratedKeys;
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			throw new QueryException("Error creating a prepared statement (query=" + query + ").", e);
		}
	}
	
	/**
	 * 
	 * @param connection
	 * @param query
	 * @param columnIndexes
	 */
	public InsertPreparedQuery(Connection connection, String query, int[] columnIndexes) {
		super();
		
		try {
			preparedStatement = connection.prepareStatement(query, columnIndexes);
			this.autoGeneratedKeys = true;
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			throw new QueryException("Error creating a prepared statement (query=" + query + ").", e);
		}
	}
	
	/**
	 * 
	 * @param connection
	 * @param query
	 * @param columnNames
	 */
	public InsertPreparedQuery(Connection connection, String query, String[] columnNames) {
		super();
		
		try {
			preparedStatement = connection.prepareStatement(query, columnNames);
			this.autoGeneratedKeys = true;
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			throw new QueryException("Error creating a prepared statement (query=" + query + ").", e);
		}
	}

	/* (non-Javadoc)
	 * @see za.co.sindi.sql.query.AbstractPreparedQuery#setFetchDirection(int)
	 */
	@Override
	public InsertablePreparedQuery setFetchDirection(int direction) {
		// TODO Auto-generated method stub
		super.setFetchDirection(direction);
		return this;
	}

	/* (non-Javadoc)
	 * @see za.co.sindi.sql.query.AbstractPreparedQuery#setFetchSize(int)
	 */
	@Override
	public InsertablePreparedQuery setFetchSize(int rows) {
		// TODO Auto-generated method stub
		super.setFetchSize(rows);
		return this;
	}

	/* (non-Javadoc)
	 * @see za.co.sindi.sql.query.AbstractPreparedQuery#setMaxFieldSize(int)
	 */
	@Override
	public InsertablePreparedQuery setMaxFieldSize(int max) {
		// TODO Auto-generated method stub
		super.setMaxFieldSize(max);
		return this;
	}

	/* (non-Javadoc)
	 * @see za.co.sindi.sql.query.AbstractPreparedQuery#setMaxRows(int)
	 */
	@Override
	public InsertablePreparedQuery setMaxRows(int max) {
		// TODO Auto-generated method stub
		super.setMaxRows(max);
		return this;
	}

	/* (non-Javadoc)
	 * @see za.co.sindi.sql.query.AbstractPreparedQuery#setQueryTimeout(int)
	 */
	@Override
	public InsertablePreparedQuery setQueryTimeout(int seconds) {
		// TODO Auto-generated method stub
		super.setQueryTimeout(seconds);
		return this;
	}

	/* (non-Javadoc)
	 * @see za.co.sindi.sql.query.AbstractPreparedQuery#setParameter(int, java.lang.Object)
	 */
	@Override
	public InsertablePreparedQuery setParameter(int parameterIndex, Object value) {
		// TODO Auto-generated method stub
		super.setParameter(parameterIndex, value);
		return this;
	}

	/* (non-Javadoc)
	 * @see za.co.sindi.sql.query.UpdatableQuery#getUpdateCount()
	 */
	@Override
	public int getUpdateCount() {
		// TODO Auto-generated method stub
		return updateCount;
	}

	/* (non-Javadoc)
	 * @see za.co.sindi.sql.query.Query#execute()
	 */
	@Override
	public void execute() {
		// TODO Auto-generated method stub
		ResultSet generatedKeysResultSet = null;
		
		try {
			updateCount = preparedStatement.executeUpdate();
			
//			//Commit
//			SQLUtils.commit(getConnection());
			
			if (autoGeneratedKeys && generatedKeysResultSetHandler != null) {
				generatedKeysResultSet = preparedStatement.getGeneratedKeys();
				generatedKeys = generatedKeysResultSetHandler.handle(generatedKeysResultSet);
			}
		} catch (SQLException e) {
			// TODO Auto-generated catch block
//			//Rollback if we found issues,
//			try {
//				SQLUtils.rollback(getConnection());
//			} catch (SQLException e1) {
//				// TODO Auto-generated catch block
//				LOGGER.log(Level.SEVERE, "Error rolling back transaction.", e1);
//			}
			
			String message = "Error executing statement for insert.";
			LOGGER.log(Level.SEVERE, message, e);
			throw new QueryException(message, e);
		} finally {
			try {
				SQLUtils.close(generatedKeysResultSet);
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				LOGGER.log(Level.WARNING, "Error closing generated keys result set.", e);
			}
			
			try {
				SQLUtils.close(preparedStatement);
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				LOGGER.log(Level.WARNING, "Error closing prepared tatement.", e);
			}
		}
	}

	/* (non-Javadoc)
	 * @see za.co.sindi.sql.query.InsertableQuery#getGeneratedKeys()
	 */
	@Override
	public Object getGeneratedKeys() {
		// TODO Auto-generated method stub
		return generatedKeys;
	}

	/* (non-Javadoc)
	 * @see za.co.sindi.sql.query.InsertablePreparedQuery#setGeneratedKeysResultSetHandler(za.co.sindi.sql.handler.ResultSetHandler)
	 */
	@Override
	public InsertablePreparedQuery setGeneratedKeysResultSetHandler(ResultSetHandler<Object> generatedKeysResultSetHandler) {
		// TODO Auto-generated method stub
		this.generatedKeysResultSetHandler = generatedKeysResultSetHandler;
		return this;
	}

	/* (non-Javadoc)
	 * @see za.co.sindi.sql.query.AbstractPreparedQuery#getStatement()
	 */
	@Override
	protected PreparedStatement getStatement() {
		// TODO Auto-generated method stub
		return preparedStatement;
	}
}
